version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10


  pre_build:
    commands:
      - npm install
#  build:
#    commands:
#       - npm install
#      - pip install --upgrade pip
#      - pip install pipenv --user
#      - pipenv install aws-sam-cli
#      - sam package --template-file template.yml --s3-bucket codepipeline-eu-west-1-428190927109 --output-template-file packaged-template.yml 
#      - tail packaged-template.yml
#      - sam deploy --template-file packaged-template.yml --stack-name pipeline-lambda-deploy --capabilities CAPABILITY_IAM      
artifacts:
  files:
    - '**/*'
